apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.label.app }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.label.app }}
    tier: {{ .Values.label.tier }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.label.app }}
      tier: {{ .Values.label.tier }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.label.app }}
        tier: {{ .Values.label.tier }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: payment
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
          - name: {{ .Values.env.name }}
            value: {{ .Values.env.value }}

          
          
